/** @jsxRuntime automatic */
/** @jsxImportSource react */
'use client';

import { Money } from '@/components/money/Money';
import type { DocumentResponse, LineItemResponse } from '@/lib/api/types/document';
import type { DocumentResult } from '@/lib/api/types/pricing';

import styles from './PrintDocument.module.css';

type PrintDocumentProps = {
  document: DocumentResponse;
  result: DocumentResult;
};

function formatDiscount(discount: LineItemResponse['discount']): string {
  if (discount.type === 'none') return '—';
  if (discount.type === 'percent') return `${discount.value} %`;
  return `$${discount.value.toFixed(2)}`;
}


function documentNumber(document: DocumentResponse): string {
  return `D-${document.issueDate.slice(0, 4)}-${document.id.slice(-6).toUpperCase()}`;
}

/** Print-optimized rendering of a document and its server-computed pricing result. */
export function PrintDocument({ document, result }: PrintDocumentProps) {
  const number = documentNumber(document);

  return (
    <main className={styles.page}>
      <div className={styles.actions}>
        <button type="button" onClick={() => window.print()}>
          Print / Save as PDF
        </button>
      </div>

      <article className={styles.sheet} aria-labelledby="document-title">
        <header className={styles.header}>
          <div>
            <div className={styles.brand}>Tallymark</div>
            <p className={styles.eyebrow}>Prepared document</p>
          </div>
          <div className={styles.documentIdentity}>
            <div className={styles.eyebrow}>Document</div>
            <h1 id="document-title">{number}</h1>
            <dl className={styles.identityDetails}>
              <div>
                <dt>Issue date</dt>
                <dd>{document.issueDate}</dd>
              </div>
              <div>
                <dt>Status</dt>
                <dd>{document.status}</dd>
              </div>
            </dl>
          </div>
        </header>

        <section className={styles.details} aria-label="Document details">
          <div>
            <h2>Prepared for</h2>
            <p>{document.customer}</p>
          </div>
          <div>
            <h2>Document</h2>
            <p>{document.title || 'Untitled document'}</p>
          </div>
        </section>

        <table className={styles.table}>
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Description</th>
              <th scope="col">Qty</th>
              <th scope="col">Unit price</th>
              <th scope="col">Discount</th>
              <th scope="col">Tax %</th>
              <th scope="col">Line total</th>
            </tr>
          </thead>
          <tbody>
            {document.lines.map((line, index) => (
              <tr key={line.id}>
                <td>{index + 1}</td>
                <td>{line.description}</td>
                <td>{line.quantity}</td>
                <td>
                  $<Money value={line.unitPrice} />
                </td>
                <td>{formatDiscount(line.discount)}</td>
                <td>{line.taxPercent === null ? '—' : String(line.taxPercent)}</td>
                <td>
                  $<Money value={result.lines[index]?.total ?? 0} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <section className={styles.summary} aria-label="Document totals">
          <p className={styles.note}>
            Amounts are in USD. Discounts are applied before tax; document totals are the
            server-computed sums of rounded line values.
          </p>
          <dl className={styles.totals}>
            <div>
              <dt>Subtotal</dt>
              <dd>
                $<Money value={document.totals.subtotal} />
              </dd>
            </div>
            <div>
              <dt>Total discount</dt>
              <dd>
                − $<Money value={document.totals.totalDiscount} />
              </dd>
            </div>
            <div>
              <dt>Total tax</dt>
              <dd>
                + $<Money value={document.totals.totalTax} />
              </dd>
            </div>
            <div className={styles.grandTotal}>
              <dt>Grand total</dt>
              <dd>
                $<Money value={document.totals.grandTotal} />
              </dd>
            </div>
          </dl>
        </section>

        <footer className={styles.footer}>
          <span>Generated by Tallymark</span>
          <span>{number}</span>
        </footer>
      </article>
    </main>
  );
}
